name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: 1.20.4
  HUGO_VERSION: 0.111.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Lint
      run: |
        make lint
    - name: Build
      run: |
        make build
    - name: Prepare SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.PAZA_PIPELINE_SSH_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.PAZA_STATIC_SITE_SERVER }} >> ~/.ssh/known_hosts
    - name: Deploy
      run: |
        rsync --archive --delete --stats public/ ${{ secrets.PAZA_PIPELINE_USERNAME }}@${{ secrets.PAZA_STATIC_SITE_SERVER }}:zan-sops/
        
