name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  GO_VERSION: 1.20.4
  HUGO_VERSION: 0.111.3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.2'
    - name: Install mdl
      run: |
        gem install mdl
    - name: Run Lint
      run: |
        make lint
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Install hugo
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name: Build
      env:
        HUGO_ENV: production
        HUGO_ENVIRONMENT: production # Backward compatiability
      run: |
        hugo --gc --minify
    - name: Prepare SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.PAZA_PIPELINE_SSH_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan -p 53667 lv-shared01.dapanel.net
    - name: Deploy
      run: |
        rsync --archive --delete --stats -e 'ssh -p 53667' public/ domains/sops.vzanartcc.net/public_html/
